name: Minecraft AI Agent

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  start-agent:
    runs-on: ubuntu-latest

    steps:

      - name: Repository yuklash
        uses: actions/checkout@v5

      - name: Node.js 24 o‘rnatish
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Node.js va npm versiyasini tekshirish
        run: |
          node --version
          npm --version

      - name: Dependencies o‘rnatish
        run: npm install

      - name: AI Agentni ishga tushirish
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          AGENT_GITHUB_TOKEN: ${{ secrets.AGENT_GITHUB_TOKEN }}

        run: npm start
